### ISSUE TITLE
Substitute tokens while loading modules

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-javaclient-util#23]
Will need to make it easy for ml-app-deployer to feed its set of properties and customTokens in

**Comment by paxtonhare** [comment]
@rjrudin FYI I did something similar on the Hub: https://github.com/marklogic/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/java/com/marklogic/hub/commands/LoadModulesCommand.java#L85
