### ISSUE TITLE
Inject MarkLogic Property Values Into Configuration Beans

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-javaclient-util#34]
As a developer
I want to TITLE
So that I can separate out individual property values from the Spring Configuration resulting in cleaner code.  

I came across this article which influenced my rationale.  
https://www.petrikainulainen.net/programming/spring-framework/spring-from-the-trenches-injecting-property-values-into-configuration-beans/

**Comment by sastafford** [comment]
Another reason for doing it this way.  I want to have more control over the Spring Configuration for my application.  Right now, most of the apps depend on BasicConfig but I would rather inject a component from ml-javaclient-util instead of being dependent upon another config.

**Comment by rjrudin** [comment]
I like all of this, I just think we should support this via a Spring-specific subclass of DatabaseClientConfig.
