### ISSUE TITLE
RoxyModuleTokenReplacer may be overstepping its bounds

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-javaclient-util#36]
DefaultModuleTokenReplacer has 

```java
private String propertyPrefix = "@ml.";
```

which is causing the token replace to always append @ml. to tokens. That seems bad for the intended default behavior.

I think it should be more like:

```java
private String propertyPrefix;
```

then in RoxyModuleTokenReplacer.java
```java
    public RoxyModuleTokenReplacer() {
        super();
        setPropertyPrefix("@ml.");
        addPropertiesSource(new FilePropertiesSource(new File("deploy/default.properties")));
        addPropertiesSource(new FilePropertiesSource(new File("deploy/build.properties")));
        addPropertiesSource(new FilePropertiesSource(new File("deploy/local.properties")));
    }
```

If this is indeed the case then I can submit a PR.

**Comment by rjrudin** [comment]
I think that makes sense. I don't think DMTR is used anywhere yet, I just made it so that I could have a Roxy-specific class with the expected Roxy file locations in it. A PR would be great, thanks.

**Comment by paxtonhare** [comment]
it's used in AppConfig.java

```java
DefaultModuleTokenReplacer r = isUseRoxyTokenPrefix() ? new RoxyModuleTokenReplacer() : new DefaultModuleTokenReplacer();
```
