### ISSUE TITLE
Load options, services, and transforms in parallel

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-javaclient-util#42]
See #41 . This should have a significant impact, at least when 2 of those 3 take a little bit of time to load.

**Comment by rjrudin** [comment]
@SoundBot This is looking straightforward. DefaultModulesLoader will have two new setters:

- setTaskExecutor - provide any Spring TaskExecutor you want for loading modules; defaults to ThreadPoolTaskExecutor, which uses java.util.concurrent
- setTaskThreadCount - defaults to 16; setting this to 1 forces sync execution; I'll add a property to ml-gradle to control this - e.g. mlModuleLoaderThreadCount

**Comment by paxtonhare** [comment]
This will be a big help for the data hub!
